// packages/svelte/src/lib/PrivacyPolicy.svelte
<script lang="ts">
import type { OpenPolicyConfig, PrivacyPolicyConfig } from "@openpolicy/core";
import { visit } from "@openpolicy/core";
import { setOverridesContext } from "./context.svelte";
import DefaultRoot from "./defaults/DefaultRoot.svelte";
import { planVisitor } from "./plan";
import RenderNode from "./RenderNode.svelte";
import type { PolicyComponents } from "./types";
import { resolveDocument } from "./usePolicyDocument.svelte";

type Props = {
	config?: OpenPolicyConfig | PrivacyPolicyConfig;
	style?: string;
} & PolicyComponents;

const props: Props = $props();

const doc = $derived(resolveDocument("privacy", props.config));
const plan = $derived(doc ? visit(doc, planVisitor) : null);

const overrides = $derived({
	Root: props.Root,
	Section: props.Section,
	Heading: props.Heading,
	Paragraph: props.Paragraph,
	List: props.List,
	ListItem: props.ListItem,
	Table: props.Table,
	TableHeaderRow: props.TableHeaderRow,
	TableHeaderCell: props.TableHeaderCell,
	TableRow: props.TableRow,
	TableCell: props.TableCell,
	Text: props.Text,
	Bold: props.Bold,
	Italic: props.Italic,
	Link: props.Link,
	Unknown: props.Unknown,
}) satisfies PolicyComponents;

setOverridesContext(() => overrides);
</script>

{#if doc && plan}
	{#snippet rootChildren()}
		<RenderNode {plan} />
	{/snippet}
	{#if props.Root}
		{@render props.Root({ node: doc, children: rootChildren })}
	{:else}
		<DefaultRoot node={doc} style={props.style}>{@render rootChildren()}</DefaultRoot>
	{/if}
{/if}

// packages/react/src/components/PrivacyPolicy.tsx
import {
	compile,
	compilePrivacyPolicy,
	type Dictionary,
	isOpenPolicyConfig,
	type Locale,
	type OpenPolicyConfig,
	type PrivacyPolicyConfig,
} from "@openpolicy/core";
import { useContext } from "react";
import { OpenPolicyContext } from "../context";
import { renderDocument } from "../render";
import type { PolicyComponents } from "../types";
import { DefaultRoot } from "./defaults";

type PrivacyPolicyProps = {
	config?: OpenPolicyConfig | PrivacyPolicyConfig;
	locale?: Locale;
	dictionary?: Dictionary;
	components?: PolicyComponents;
	style?: unknown;
};

export function PrivacyPolicy({
	config: configProp,
	locale,
	dictionary,
	components,
	style,
}: PrivacyPolicyProps) {
	const { config: contextConfig } = useContext(OpenPolicyContext);
	const baseConfig = configProp ?? contextConfig ?? undefined;
	if (!baseConfig) return null;
	const config = locale ? { ...baseConfig, locale } : baseConfig;
	const doc = isOpenPolicyConfig(config)
		? compilePrivacyPolicy(config, dictionary)
		: compile({ type: "privacy", ...config }, dictionary);
	if (!doc) return null;
	const Root = components?.Root ?? DefaultRoot;
	return (
		<Root node={doc} style={style}>
			{renderDocument(doc, components)}
		</Root>
	);
}
